apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: simpleapps.demo.mycompany.com
spec:
  group: demo.mycompany.com
  scope: Namespaced
  names:
    plural: simpleapps
    singular: simpleapp
    kind: SimpleApp
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              image:
                type: string
              replicas:
                type: integer
